data:
  # paths_to_file_root: /data/jjhong96/LundNet_Graph/FourProngV2_MultiClassTrain/data_*.root
  # paths_to_file_graphs: /data/jjhong96/LundNet_Graph/FourProngV2_MultiClassTrain/graphs_*_pt
  paths_to_file_root: /data/jjhong96/LundNet_Graph/FourProngV2_ExKtSubJ_MultiClassTrain/data_*.root
  paths_to_file_graphs: /data/jjhong96/LundNet_Graph/FourProngV2_ExKtSubJ_MultiClassTrain/graphs_*_pt

# ROOT tree / branches
tree_name: "FlatSubstructureJetTree"
branch_pt: "fjet_pt"
branch_mass: "fjet_m"
branch_label: "fjet_nQuark10_labels" # fjet_truth_label, fjet_nProng_labels, fjet_nQuark_labels, fjet_nQuark10_labels, fjet_nQuark8_labels, fjet_nQuark8_loose_iso_labels, fjet_nQuark8_medium_iso_labels, fjet_nQuark8_tight_iso_labels

do_subJ_Regression: true
branch_subJ_pt: "fjet_ExKt_subJ_pt"
branch_subJ_eta: "fjet_ExKt_subJ_eta"
branch_subJ_phi: "fjet_ExKt_subJ_phi"

label_per_dsid:
  do_label_per_dsid: false # Only for SM background training
  label_dsid_map:
    801168: 1 # These are QCD samples, use label=1
    801169: 1
    801170: 1
    801171: 1
    801172: 1
    801173: 1
    700843: 2 # Wqq
    700849: 2 # Zqq
    700855: 2 # Zbb
    601237: 3 # ttbar_allhad
    # 560083: 4 # HH4W
    560088: 4 # SS4W 200
    560089: 4 # SS4W 300
    560090: 4 # SS4W 400
    560091: 4 # SS4W 500
    560092: 4 # SS4W 600

# Labels
labels: [1, 2, 3, 4] # This label will be saved in the graphs
signal_label: 4 # If event_weight_signal_flat_pT is used, this label will be treated as signal for flat-pT weighting
label_map: null  # optional mapping, e.g. {1:3, 10:1, 2:2, 12:4} # Move truth_labels to {1,2,3,4} and QCD (10) to 1
# Label mapping happens before the filtering of labels
# label_map: null for no mapping

# Jets per class
# n_jets_per_class: 1531215
# n_jets_per_class: 1169782 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6. Maximum for 2dFlat
n_jets_per_class: 1000000
# n_jets_per_class: 950723 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6
# n_jets_per_class: 338444 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6. For S300 signal
# n_jets_per_class: 100000 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6
# n_jets_per_class: 10000 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6
# n_jets_per_class: 5000 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6
# n_jets_per_class: 1000 # Number of jets per class to use (None for all), minimum 971255, maximum 1.5e+6

# Reweighting
reweight_mode: "flat_pt_mass_2d"  # "none", "flat_pt", "flat_mass", "flat_pt_mass_2d", "event_weight", "event_weight_signal_flat_pT"
pt_range: [350, 2500] # [min, max] in GeV
pt_binN: 100
mass_range: [40, 600] # [min, max] in GeV
mass_binN: 50

# Output
# output_dir: "/data/jjhong96/LundNet_Graph/FourProngV2_MultiClassTrain/Shuffled_Graphs_NProng_2dFlat/" # NProng, NQuark10, NQuark8, NQuark8_Loose_Iso, NQuark8_Medium_Iso, NQuark8_Tight_Iso 
output_dir: "/data/jjhong96/LundNet_Graph/FourProngV2_MultiClassTrain_ReweightFix/Shuffled_Graphs_ExKtSubJ_NoHWW_NQuark10_2dFlat/"
histogram_filename: "reweight_histograms.npz"

# Class balancing
reference_label: 4 # Label to use as a reference class for balancing. E.g) I'll scale class 2 sum of weight to match class 1 sum of weight

# Split
test_fraction: 0.1
n_splits_files: 20

random_seed: 42